/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package fp.image.lang;

import java.time.Duration;
import java.time.Instant;
import java.util.ArrayList;
import java.util.Arrays;

public class Runner {

    private Instant start;
    private Instant end;

    public Runner() {
        start = Instant.now();
    }

    public static void main(String[] args) {
        ArrayList<String> arguments = new ArrayList<>();
        arguments.addAll(Arrays.asList(args));
        Runner i = new Runner();

        if (args.length > 0) {
            i.interpret(args[0]);
        }
        else {
            i.interpret("");
        }
    }

    private void interpret(String script) {
        this.welcomeMsg();

        this.benchMark();

        this.completeMsg();
    }

    private void helpMsg() {

        this.benchMark();

    }

    private void benchMark() {
        System.out.println("Benchmarking...");
        for (int i = 0; i < 1000000000; ++i) {
            int r = i % 3;
        }
    }


    private void welcomeMsg() {
        System.out.println("Working...");
        start = Instant.now();
    }

    private void completeMsg() {
        this.end = Instant.now();
        System.out.println("Finished!");
        System.out.println("Elapsed time: "+ (Duration.between(start, end).toMillis()*0.001) + " second(s).");
    }
}
